### PR TITLE
Culture sensitivity

### LINKED ISSUE #138: DirectoryExtensions.TryGetDateTime() fails in some cultures
Issue is this function calls [DateTime.TryParseExact()](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tryparseexact?view=netframework-4.7.2#System_DateTime_TryParseExact_System_String_System_String___System_IFormatProvider_System_Globalization_DateTimeStyles_System_DateTime__) with a null format provider. The parse therefore can only succeed if the current culture uses the same separators as the file containing the metadata. From a quick review it looks to me like the intent is to perform invariant parsing, in which case the fix would be to pass CultureInfo.InvariantCulture rather than null.

Workaround is to reimplement the method's code. Personally, I hit this on Arabic so setting CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("ar") on a test thread should provide repro.

### PR DESCRIPTION
**Pull request by patricksadowski**
Closes #138

There are still some string concatenation that do not use an invariant output format. But the main points of the issue are fixed.

### CODE REVIEW

File: .editorconfig [hunk 1]
```diff
@@ -222,11 +222,6 @@ dotnet_diagnostic.CA1303.severity = none                          # Literal stri
 # working around bug
 dotnet_diagnostic.RS0041.severity = none                          # Public members should not use oblivious types
 
-# TODO review these diagnostics as many/all are probably valid
-dotnet_diagnostic.CA1304.severity = none                          # Method behaviour depends upon user's locale
-dotnet_diagnostic.CA1305.severity = none                          # Method behaviour depends upon user's locale
-dotnet_diagnostic.CA1307.severity = none                          # Method behaviour depends upon user's locale
```
Comment (drewnoakes) [inline .editorconfig:228]: Is the default "warning" here?

File: MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs [hunk 2]
```diff
@@ -23,7 +24,7 @@ protected override void ProcessRecord()
         {
             base.ProcessRecord();
 
-            WriteVerbose($"Extracting metadata from file: {FilePath}");
+            WriteVerbose(string.Format(CultureInfo.InvariantCulture, "Extracting metadata from file: {0}", FilePath));
```
Comment (drewnoakes) [inline MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: Were these transformations performed manually or via automation?

Comment (drewnoakes) [inline MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: Pardon my ignorance, but how can culture influence string concatenation? For example, other cases were previously `$"Foo {nameof(Bar)}", which I believe the compiler is within rights to optimise to `"Foo Bar"` at compile time.

**Comment by drewnoakes** [comment]
@patricksadowski thanks for taking the initiative on this. Looks good. Just a few questions to help me understand.

File: .editorconfig (hunk 1 above)
Comment (patricksadowski) [reply .editorconfig:228]: I got warnings. The [docs](https://docs.microsoft.com/visualstudio/code-quality/ca1307) categorizes the rules as globalization warnings.

File: MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs (hunk 2 above)
Comment (patricksadowski) [reply MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: Hand made with ♥. I don't know any tool for that.

Comment (patricksadowski) [reply MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: String interpolation uses the current culture. There are issues for cases like
```csharp
var bar = 1.23;
$"Foo {bar}"
```
but (and you are right) not for cases like:
```csharp
var bar = 1.23;
$"Foo {nameof(bar)}"
```
If you like I revert the changes for the cases with `nameof`.

Comment (patricksadowski) [reply MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: Finally also cases like
```csharp
var bar = 1.23;
string.Concat("Foo ", bar);
"Foo " + bar;
```
are not taking culture into account.

Comment (drewnoakes) [reply MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: I thought perhaps the analyzer came with a codefix.

Comment (drewnoakes) [reply MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: Did you only fix warnings produced by the analyzer, or did you search for all string interpolation?

I don't see warnings when reverting some of these changes. Where formattable types are involved, fair enough, but many of these changes involve only strings and the result is a reduction in both readability and performance.

https://sharplab.io/#v2:D4AQjAbABCBMUGECwAoA3qqWYGYaXwAYoBZMACgEsA7AFykoEooBeAPigBIAiAQQCEEUNJQC+UACIBRAGLcA3Jmwg84aOGIlY5DVADOzdlz6Dhe8dLmKU2XPnVhNOHY/2GOPAULTUAhgFsAUwB7ADNyAwtZBSUsWLs1IlIAFio6BnciADoZYIAnf19achNvQii5ABoM61sVeySSAFYXYgNWDg0c/MLi0uFyyWjqg1rlVQJdEghWtw7s3IKikq8Biu5qvyCwiMZGa1EgA

I should point out that I'm also trying to work out whether the analyzer can be improved in order to provide feedback to that team.

Comment (patricksadowski) [reply MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: Great idea!

Comment (patricksadowski) [reply MetadataExtractor.PowerShell/ExtractMetadataCmdlet.cs:27]: Visual studio helped me to find all places. I didn't get warnings. Knowing that interpolated strings use the current culture I tried to find them all. Validation was done with `git grep`.

I found another notation the keep the readability.
```csharp
FormattableString.Invariant($"ABC {i} DEF");
```
Do you like that?

**Comment by drewnoakes** [comment]
My original review was focussed on how the analyzer works and whether it could be improved.

Thinking about this some more I realise something deeper. #138 is about a bug in _parsing_ where the input is known to be invariant, but parsing code relies upon the current culture.

This PR fixes that, however it also forces _all formatted output_ to use invariant culture, which is not correct. The library should produce output strings that match the user's culture.

If this was merged as-is, all strings would appear in invariant culture (which is essentially en-US).

**Comment by patricksadowski** [comment]
> This PR fixes that, however it also forces _all formatted output_ to use invariant culture, which is not correct. The library should produce output strings that match the user's culture.

Because of your https://github.com/drewnoakes/metadata-extractor-dotnet/issues/138#issuecomment-624027571 I tried to fix the whole issue. I think I have another unterstanding of culture sensitivity.
If the app outputs English text then also numbers should be formatted like English numbers: `The value equals 1.23` instead of `The value equals 1,23` (German).
If the library supports multiple languages then text shoud be available in each supported language: `The value equals 1.23` _and_ `Der Wert ist gleich 1,23`

To get this done I propose to fix only the main bug of the issue. Your https://github.com/drewnoakes/metadata-extractor-dotnet/issues/138#issuecomment-624027571 should be done in a second PR oder issue. Is it OK for you?

**Comment by drewnoakes** [comment]
> Because of your comment I tried to fix the whole issue

Yeah sorry, I hadn't thought the implications through when I wrote that. It wasn't intended as a strong statement. It may be possible to configure the analyzer to do what we want (via attributes or patterns in the `.editorconfig` file).

> If the app outputs English text then also numbers should be formatted like English numbers

This is debatable. I'm pretty sure if this were changed then we'd see bug reports. Ideally all output strings would be localised.

> To get this done I propose to fix only the main bug of the issue.

That's certainly the safest way forward here. Perhaps we add a bit more context to the TODO in the `.editorconfig` file too.

**Comment by drewnoakes** [comment]
Thanks very much Patrick.
