### PR TITLE
Fixes Issue #328

### LINKED ISSUE #328: Reading UTF-8 from iTXt PNGChunk
In PNGMetadataReader.cs mentions:

        /// Note that "iTXt" chunks use UTF-8 encoding (https://www.w3.org/TR/PNG/#11iTXt).

And the document at that URL states:

> The translated keyword and text both use the UTF-8 encoding

However at L:249, the keyword is read using _latin1Encoding, and the text is read in ReadTextDirectory using _latin1Encoding.

This leads to UTF-8 characters such as emoji being decoded improperly.

### PR DESCRIPTION
**Pull request by RupertAvery**
Fixes #328

Parse the keyword and text directory using utf8 encoding if PNG Chunk Type is iTXt

### CODE REVIEW

File: MetadataExtractor/Formats/Png/PngMetadataReader.cs [hunk 1]
```diff
@@ -90,6 +90,7 @@ public static DirectoryList ReadMetadata(Stream stream)
         /// For more guidance: http://www.w3.org/TR/PNG-Decoders.html#D.Text-chunk-processing
         /// </summary>
         private static readonly Encoding _latin1Encoding = Encoding.GetEncoding("ISO-8859-1");
+        private static readonly Encoding _utf8Encoding = Encoding.GetEncoding("UTF-8");
```
Comment (drewnoakes) [inline MetadataExtractor/Formats/Png/PngMetadataReader.cs:93]: I think we could use `Encoding.UTF8`, and inline the field.

**Review by drewnoakes — COMMENTED** [review]
Thanks, this looks great. I'll try it on the regression test data set before merging.

File: MetadataExtractor/Formats/Png/PngMetadataReader.cs [hunk 2]
```diff
@@ -248,7 +249,7 @@ private static IEnumerable<Directory> ProcessChunk(PngChunk chunk)
             else if (chunkType == PngChunkType.iTXt)
             {
                 var reader = new SequentialByteArrayReader(bytes);
-                var keyword = reader.GetNullTerminatedStringValue(maxLengthBytes: 79).ToString(_latin1Encoding);
+                var keyword = reader.GetNullTerminatedStringValue(maxLengthBytes: 79).ToString(_utf8Encoding);
```
Comment (drewnoakes) [inline MetadataExtractor/Formats/Png/PngMetadataReader.cs:252]: There's actually now an issue slightly below here. The `bytesLeft` value was based on the length of the string in bytes, which for latin1 is the same as the length of the string in characters. With UTF-8 that's not the case. I'll patch this up and push to your PR.

**Comment by drewnoakes** [comment]
I ran this against the regression test data set and it now successfully parses a bunch of previously broken values. I see no downside to this anywhere. Great stuff, thanks!

**Review by drewnoakes — APPROVED** [review]
